#!/bin/sh
#
# ### install
#
# *A script to link version controlled bin scripts to links in $HOME/bin
#
# This script links all files in the "bin" directory into the $HOME/bin
# directory of the acting user. Any files with the same names in $HOME/bin will
# not be overridden.

# Script Constants
BIN_DIR="$( cd "$( dirname "$0" )" && pwd )/bin"
HOME_BIN="$HOME/bin"

# Make sure we have a $HOME/bin
if [ -z $HOME_BIN ]; then
	echo "Could not identify the $HOME_BIN Directory"
	exit 1
fi

# When there are no files in the DOT_DIR with the matching DOT_PREFIX, sh
# returns that expression as a string instead of a list of files. If that
# happens, catch it and quit instead of creating problems
dot_files_exist="$(ls $BIN_DIR/* 2>/dev/null)"
if [ "$dot_files_exist" = "" ]; then
	echo "No dot files found to copy into \$HOME"
	exit 2
fi

for script in $BIN_DIR/*
do
	# Get the filename
	current_file=$(basename $script)

    # Link it!
	ln -s $BIN_DIR/$current_file $HOME_BIN/$current_file
done
